name: ci_cd pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  app_test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: setup python 
       uses: actions/setup-python@v3
       with : 
       python-version: '3.9'

     - name : install requirement 
       runs : pip install -r requirements.txt

     - name : run test 
       uses : pytest
    
  app_deploy :
    needs : app_test
    runs-on : ubuntu-latest
    steps :
     - name : Checkout code
       uses : actions/checkout@v4

     - name : set up docker 
       uses : docker/setup-buildx-action@v2

     - name : login to docker
       uses : docker/login-action@v2
       with :
         username : ${{ secrets.DOCKER_USERNAME }}
         password : ${{ secrets.DOCKER_PASSWORD }}

     - name : login and then push docker image
       uses : docker/build-push-action@v4
       with:
        context: .
        file : ./DockerFile
        push : true
        tags : ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest

     - name : image digest 
       run: echo ${{ steps.build-and-publish.outputs.digest }}

           
